import RequestData from "./services/RequestData.js";

document.addEventListener('click', (e) => {
    if (e.target.matches("#getoutlogin")) {
        getoutlogin();
    }
    if (e.target.matches("#getoutindex")) {
      geterror(true);
    }
})


const getoutlogin = () => {
  const session = {
    session: "jsdjsad"
  };

  requestPost("../SRC/JS/Data.php", session);
};

/*
  This code is calling the Request Data function and passing in an object with a url 
  options sucess and show Error The url is passed into the Request Data function which will make a request to that URL using the options provided If there are no errors then it will call the sucess callback otherwise it calls show Error
   - generated by stenography autopilot [ 🚗👩‍✈️ ]
*/

const requestPost = (url, data) => {
  RequestData({
    url: url,
    options: {
      method: "POST",
      headers: {
        "Content-Type": "application/x-www-form-urlencoded",
      },
      body: JSON.stringify(data),
    },
    sucess: () => {
      console.log("request");
    },
    showError: (error) => {
      console.log({ error });
    },
  });

}


const geterror = (error) => {
    if (error) {
        window.location.href = "../index.php";
        alert("Contraseña o usuario incorrecto");
    }
};